on: push
name: Build and Publish
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Test
      uses: actions/action-builder/shell@master
      with:
        entrypoint: make
        args: test
    - name: Lint
      uses: actions/action-builder/shell@master
      with:
        entrypoint: make
        args: lint
    - name: Build
      uses: actions/action-builder/docker@master
      with:
        entrypoint: make
        args: build
    - name: Docker Login
      uses: actions/docker/login@master
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_REGISTRY_URL: "docker.pkg.github.com"
    - name: Publish
      uses: actions/action-builder/docker@master
      with:
        entrypoint: make
        args: publish
